defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: NLP lab
subtitle: Computer Science Department - University of Engineering and Technology, VNUH

# Side Menu Links
menu:
  - text: Giới Thiệu
    link: /
    icon: ""
    
  - text: Tin Tức
    link: /news
    icon: ""

  - text: Thành Viên
    link: /members
    icon: ""

  - text: Công Bố khoa học
    link: /publications
    icon: ""

  - text: Tài Nguyên
    link: /resources
    icon: ""
    
  - text: Tuyển Dụng
    link: /recruitment
    icon: ""
    
  - text: Liên hệ
    link: /contact
    icon: ""
# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/
    icon: fab fa-github-square



    
