defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: NLP lab
subtitle: Computer Science Department - University of Engineering and Technology, VNUH

# Side Menu Links
menu:
  - text: News
    link: /
    icon: ""

  - text: Intros
    link: /introduction
    icon: ""

  - text: Members
    link: /contact
    icon: ""

  - text: My Resume
    link: /resume
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/christianezeani
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/christianezeani
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/christian.ezeani.cyb
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/christianezeani
    icon: fab fa-twitter


    
