defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: NLP lab
subtitle: Computer Science Department - University of Engineering and Technology, VNUH

# Side Menu Links
menu:
  - text: Tin Tức
    link: /
    icon: ""

  - text: Giới thiệu
    link: /introduction
    icon: ""

  - text: Thành Viên
    link: /members
    icon: ""

  - text: Báo cáo khoa học
    link: /publications
    icon: ""

  - text: Liên hệ
    link: /contact
    icon: ""
# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/
    icon: fab fa-github-square



    
